---
- name: ensure that phpfarm is present
  become: yes
  become_method: sudo
  git:
    repo: https://github.com/DemacMedia/phpfarm.git
    dest: /opt/phpfarm
    update: no
    clone: yes

- name: ensure that php5.6 is compiled by phpfarm
  become: yes
  become_method: sudo
  command: /opt/phpfarm/src/main.sh 5.6.20

- name: ensure that xdebug for php5.6 is present
  become: yes
  become_method: sudo
  git:
    repo: git://github.com/xdebug/xdebug.git
    dest: /usr/lib/xdebug
    update: no
    clone: yes

- name: run phpize php5.6 xdebug compile step
  become: yes
  become_method: sudo
  command: /opt/phpfarm/inst/php-5.6.20/bin/phpize
  args:
    chdir: /usr/lib/xdebug
  
- name: run configure php5.6 xdebug compile step
  become: yes
  become_method: sudo
  command: ./configure --with-php-config=/opt/phpfarm/inst/php-5.6.20/bin/php-config
  args:
    chdir: /usr/lib/xdebug

- name: run make php5.6 xdebug compile step
  become: yes
  become_method: sudo
  make: chdir=/usr/lib/xdebug

- name: run make install target php5.6 xdebug compile step
  become: yes
  become_method: sudo
  make: chdir=/usr/lib/xdebug target=install

- name: ensure that php5.6 ini file is present
  become: yes
  become_method: sudo
  copy:
    src: php5.6.20.ini
    dest: /opt/phpfarm/inst/php-5.6.20/etc/php.ini

- name: backup php5.6 ini file to lib
  become: yes
  become_method: sudo
  copy:
    remote_src: true
    src: /opt/phpfarm/inst/php-5.6.20/etc/php.ini
    dest: /opt/phpfarm/inst/php-5.6.20/lib/php.ini

- name: ensure that php5.6 php-fpm config file is present
  become: yes
  become_method: sudo
  copy:
    src: php-fpm-5.6.conf
    dest: /opt/phpfarm/inst/php-5.6.20/etc/php-fpm.conf

- name: ensure that php5.6 initd script is present
  become: yes
  become_method: sudo
  copy:
    src: php-init.d-5.6.sh
    dest: /etc/init.d/php-5.6
    mode: 0755

- name: ensure that initd script is set in rc.d configuration
  become: yes
  become_method: sudo
  command: update-rc.d php-5.6 defaults

- name: restart php-5.6 php-fpm service
  become: yes
  become_method: sudo
  service: name=php-5.6 state=restarted
