---
- name: ensure that local apt cache is up to date
  become: yes
  become_method: sudo
  apt: update_cache=yes

- name: ensure that PHP compile prerequisites are present
  become: yes
  become_method: sudo
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libbz2-dev
    - libmysqlclient-dev
    - libxpm-dev
    - libmcrypt-dev
    - libcurl4-gnutls-dev
    - libxml2-dev
    - libjpeg-dev
    - libpng12-dev
    - libssl-dev
    - pkg-config
    - libreadline-dev
    - curl
    - autoconf
    - libicu-dev
    - libxslt-dev

- name: ensure .bashrc config file exists
  copy:
    src: .bashrc
    dest: /home/vagrant/.bashrc
    owner: vagrant
    group: vagrant
